import{a as f,S as g,i as d}from"./assets/vendor-64b55ca9.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const s of t.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&n(s)}).observe(document,{childList:!0,subtree:!0});function r(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function n(e){if(e.ep)return;e.ep=!0;const t=r(e);fetch(e.href,t)}})();f.defaults.baseURL="https://pixabay.com/";const L="42373349-27b23dee84583d41aca0b8d31";async function p(i,o=1){const r=await f.get("api/",{params:{key:L,per_page:15,page:o,q:i,image_type:"photo",orientation:"horizontal",safesearch:!0}});return console.log(r),r.data}const w=new g(".gallery",{captionDelay:250,captionsData:"alt",enableKeyboard:!0});function h(i){const o=i.map(({webformatURL:r,largeImageURL:n,tags:e,likes:t,views:s,comments:y,downloads:b})=>`<ul>
        <li><a href="${n}"><img src="${r}" alt="${e}"/></a></li>
          <li><p>Likes ${t}</p></li>
          <li>
            <p>Views ${s}</p>
          </li>
          <li><p>Comments ${y}</p></li>
          <li><p>Downloads ${b}</p></li>
        </ul>`);a.insertAdjacentHTML("beforeend",o.join("")),w.refresh()}new g(".gallery a",{captionDelay:250,captionsData:"alt",enableKeyboard:!0});const a=document.querySelector(".gallery"),S=document.querySelector("input"),H=document.querySelector("form"),c=document.querySelector(".loader-button");document.querySelector(".loader");const m=15;let u="",l=1,P;c.addEventListener("click",C);H.addEventListener("submit",v);function q(){d.show({title:"Error",message:"Please, enter a non-blank line",titleSize:"16px",titleLineHeight:"150%",messageSize:"16px",messageLineHeight:"150%",backgroundColor:"#ef4040",position:"bottomRight"})}function x(){d.show({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",titleSize:"16px",titleLineHeight:"150%",messageSize:"16px",messageLineHeight:"150%",backgroundColor:"#ef4040",position:"bottomRight"})}function R(){d.show({title:"Error",message:"We're sorry, but you've reached the end of search results.",titleSize:"16px",titleLineHeight:"150%",messageSize:"16px",messageLineHeight:"150%",backgroundColor:"#ef4040",position:"bottomRight"})}async function v(i){i.preventDefault();const o=i.currentTarget.elements.query.value.trim();try{if(o===""){a.innerHTML="",q(),c.hidden=!0;return}u=o;const{hits:r,totalHits:n}=await p(u,l);if(n>0){h(r);const{height:e}=a.getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"}),S.value="",c.hidden=!1,P=Math.ceil(n/m)}else a.innerHTML="",x()}catch(r){console.error(r)}}async function C(){try{l+=1;const{hits:i,totalHits:o}=await p(u,l);h(i);const r=a.firstElementChild.getBoundingClientRect();window.scrollBy({top:r.height,behavior:"smooth"}),Math.ceil(o/m)!==l&&(c.hidden=!0,R())}catch(i){console.error(i)}}
//# sourceMappingURL=commonHelpers.js.map
